# Generated by Django 5.2.16 on 2026-07-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=100)),
                ('measurement', models.CharField(max_length=100)),
                ('current_stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_purchased_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_purchased_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.item')),
            ],
            options={
                'unique_together': {('item', 'length', 'measurement')},
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesmen', to='api.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
    ]
