# Generated by Django 5.2.16 on 2026-07-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_first_name_company_last_name_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
