# Generated by Django 5.2.16 on 2026-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_purchase_date_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
