# Generated by Django 5.2.16 on 2026-07-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_party_purchase_party_sale_party'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemvariant',
            unique_together={('item', 'length')},
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='measurement',
        ),
    ]
