# Generated by Django 5.2.16 on 2026-08-04 11:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_saleitem_cost_price_at_sale"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="itemvariant",
            name="variant_item_size_ci_unique",
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="itemvariant",
            unique_together={("item", "size", "price")},
        ),
        migrations.AddConstraint(
            model_name="itemvariant",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("size"),
                models.F("item"),
                models.F("price"),
                name="variant_item_size_price_ci_unique",
            ),
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="avg_purchase_price",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="total_purchased_qty",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="total_purchased_value",
        ),
    ]
