# Generated by assistant
from django.db import migrations, models
import django.db.models.functions as funcs


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_itemvariant_variant_item_size_ci_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="party_type",
            field=models.CharField(
                choices=[("purchase", "Purchase"), ("sale", "Sale")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="party",
            options={"unique_together": {("company", "name", "party_type")}},
        ),
        migrations.AddConstraint(
            model_name="party",
            constraint=models.UniqueConstraint(
                funcs.Lower("name"),
                "company",
                "party_type",
                name="party_company_name_type_ci_unique",
            ),
        ),
    ]
