# Generated by assistant
from django.db import migrations


def set_party_types(apps, schema_editor):
    Party = apps.get_model("api", "Party")
    Purchase = apps.get_model("api", "Purchase")
    Sale = apps.get_model("api", "Sale")
    Quotation = apps.get_model("api", "Quotation")

    problematic = []

    for party in Party.objects.all():
        # Skip if already typed
        if party.party_type:
            continue
        has_purchase = Purchase.objects.filter(party_id=party.id).exists()
        has_sale = (
            Sale.objects.filter(party_id=party.id).exists()
            or Quotation.objects.filter(party_id=party.id).exists()
        )
        if has_purchase and not has_sale:
            party.party_type = "purchase"
            party.save(update_fields=["party_type"])
        elif has_sale and not has_purchase:
            party.party_type = "sale"
            party.save(update_fields=["party_type"])
        elif not has_purchase and not has_sale:
            # Default to purchase for orphaned parties
            party.party_type = "purchase"
            party.save(update_fields=["party_type"])
        else:
            # Referenced by both purchases and sales/quotations -> stop and let user resolve
            problematic.append((party.id, party.name, party.contact))

    if problematic:
        msg_lines = [f"Overlapping party (id,name,contact): {p}" for p in problematic]
        raise RuntimeError(
            "Overlapping parties found; please resolve them before running migrations:\n"
            + "\n".join(msg_lines)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_add_party_type"),
    ]

    operations = [
        migrations.RunPython(set_party_types, reverse_code=migrations.RunPython.noop),
    ]
