# Generated by Django 5.2.16 on 2026-08-05 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_migrate_party_types'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='party',
            name='party_company_name_ci_unique',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='party',
            field=models.ForeignKey(limit_choices_to={'party_type': 'purchase'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='api.party'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='party',
            field=models.ForeignKey(limit_choices_to={'party_type': 'sale'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='api.party'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='party',
            field=models.ForeignKey(limit_choices_to={'party_type': 'sale'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.party'),
        ),
    ]
