# Generated by Codex on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_party_party_company_name_ci_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesman",
            name="contact",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="salesman",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
